### ISSUE TITLE
`RepositoryFiles.showRaw` returns `404 File Not Found` but `RepositoryFiles.show` works

### ISSUE THREAD

**Issue by EvHaus** [jdalrymple/node-gitlab-api#62]
For some reason the following request:

```
const projectId = 123;
const filePath = 'package.json';
const ref = 'master';

this.api.RepositoryFiles.showRaw(projectId, filePath, ref)
```

Fails with:

```
UnhandledPromiseRejectionWarning: StatusCodeError: 404 - {"message":"404 Project Not Found"}
    at new StatusCodeError (/Users/ev.haus/Git/thing/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Users/ev.haus/Git/thing/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Users/ev.haus/Git/thing/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Users/ev.haus/Git/thing/node_modules/request/request.js:186:22)
    at Request.emit (events.js:180:13)
    at Request.emit (domain.js:422:20)
    at Request.<anonymous> (/Users/ev.haus/Git/thing/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:180:13)
    at Request.emit (domain.js:422:20)
    at IncomingMessage.<anonymous> (/Users/ev.haus/Git/naggie/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at IncomingMessage.emit (domain.js:422:20)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
```

But if I change the code to:

```
const projectId = 123;
const filePath = 'package.json';
const ref = 'master';

this.api.RepositoryFiles.show(projectId, filePath, ref)
    .then((response) => {
        return this.api.Repositories.showBlobRaw(projectId, response.blob_id);
    });
```

Then it works just fine.

Any idea what could be wrong?

**Comment by jdalrymple** [comment]
Tested a direct request and it worked. Weird. ill investigate further tonight!

**Comment by jdalrymple** [comment]
Tested it with the library as well and didnt run into trouble :confused:

**Comment by EvHaus** [comment]
Can you think of anything special about my Gitlab project that would cause this behavior?

**Comment by jdalrymple** [comment]
Hmm, well I tested with a public project, I can try with a private one and see if that makes a difference. I'll even try with a package.json file to see if it's the file but I doubt it. 

Is the project you noticed this with public ?

**Comment by EvHaus** [comment]
No, I'm using a private project on a local Gitlab server.

**Comment by jdalrymple** [comment]
Hmm maybe that's it. Do you have a gitlab.com account ?

**Comment by EvHaus** [comment]
We're on

```
GitLab 9.5.4
GitLab Shell 5.8.0
GitLab Workhorse v3.0.0
GitLab API v4
```

**Comment by jdalrymple** [comment]
I know its a hassle but could you try making a direct http request to that endpoint to your gitlab instance to see if it works?

**Comment by EvHaus** [comment]
Looks like it's a bug with the Gitlab API itself because a direct HTTP request fails as well.

```

GET /api/v3/projects/229/repository/files/package.json/?ref=dev
// => Works!

GET /api/v3/projects/229/repository/files/package.json/raw?ref=dev
// => Fails with `{"statusCode":404,"body":"{\"message\":\"404 File Not Found\"}"`
```

Will close this issue and open up a ticket with Gitlab.

Thanks for your help!
